Repository adzai/chatbot, pull requests merged in 2020-11, with the labels that each got.

#20 011 data structure for keywords and synonyms
  data/synonyms.json
Labels: data

#33 032 final data
  data/Bertramka.json
  data/data-en.json
Labels: data

#31 028 processing identified keywords
  src/chatbot/find_park_data.clj
  test/chatbot/core_test.clj
Labels: priority

#49 #13: Update README
  README.md
Labels: documentation

#52 #51: fix cyclic dependencies
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
  src/chatbot/greet.clj
  src/chatbot/identify_keyword.clj
  src/chatbot/parse.clj
  test/chatbot/core_test.clj
Labels: bug

#39 Updated main loop
  src/chatbot/core.clj
Labels: priority

#55 053 replies formatting
  project.clj
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
  src/chatbot/get_data.clj
  src/chatbot/greet.clj
  src/chatbot/main_loop.clj
  src/chatbot/user_utils.clj
  test/chatbot/core_test.clj
Labels: enhancement

#58 048 goodbye message
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
Labels: enhancement
