Repository adzai/chatbot, pull requests merged in 2020-12, with the labels that each got.

#59 047 parse input in loop
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/identify_keyword.clj
  test/chatbot/core_test.clj
Labels: enhancement

#60 #56: fix crash on input
  data/synonyms.json
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
  src/chatbot/parse.clj
  src/chatbot/user_utils.clj
Labels: bug

#63 Added description of chatbot's functionality
  docs/index.html
Labels: documentation

#62 061 cleanup
  data/Bertramka.json
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
  src/chatbot/identify_keyword.clj
  src/chatbot/parse.clj
  src/chatbot/user_utils.clj
  test/chatbot/core_test.clj
Labels: enhancement

#65 057 Park history
  data/park-history.json
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
Labels: enhancement

#64 Allow the user to choose and change the park
  CHANGELOG.md
  README.md
  docs/index.html
  project.clj
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/find_park_data.clj
  src/chatbot/park_utils.clj
  src/chatbot/parse.clj
  src/chatbot/user_utils.clj
  test/chatbot/core_test.clj
Labels: enhancement
