Repository adzai/chatbot, pull requests merged in 2021-01, with the labels that each got.

#78 Documentation pages
  .github/workflows/clojure.yml
  doc/chatbot.bot_utils.html
  doc/chatbot.core.html
  doc/chatbot.get_data.html
  doc/chatbot.identify_keyword.html
  doc/chatbot.levenshtein.html
  doc/chatbot.park_utils.html
  doc/chatbot.parse.html
  doc/chatbot.user_utils.html
  doc/css/default.css
  doc/css/highlight.css
  doc/index.html
  doc/intro.html
  doc/intro.md
  doc/js/highlight.min.js
  doc/js/jquery.min.js
  doc/js/page_effects.js
  docs/style.css
  project.clj
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/get_data.clj
  src/chatbot/identify_keyword.clj
  src/chatbot/park_utils.clj
  src/chatbot/user_utils.clj
Labels: documentation

#84 #69: add an errors printed in a row counter and offer help instead of…
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
Labels: enhancement

#72 Web server
  docs/chatbot.bot_utils.html
  docs/chatbot.core.html
  docs/chatbot.decision_tree.html
  docs/chatbot.get_data.html
  docs/chatbot.identify_keyword.html
  docs/chatbot.levenshtein.html
  docs/chatbot.park_utils.html
  docs/chatbot.parse.html
  docs/chatbot.user_utils.html
  docs/index.html
  docs/intro.html
  docs/web.backend.html
  docs/web.db.html
  docs/web.pages.html
  project.clj
  resources/public/script.js
  resources/public/style.css
  src/chatbot/core.clj
  src/chatbot/park_utils.clj
  src/web/backend.clj
  src/web/db.clj
  src/web/pages.clj
Labels: enhancement

#95 Updated github pages
  docs/intro.md
Labels: documentation

#94 Test and refactoring
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/decision_tree.clj
  test/chatbot/core_test.clj
Labels: enhancement

#93 Error counter enhancement
  src/chatbot/bot_utils.clj
  src/chatbot/core.clj
  src/chatbot/user_utils.clj
Labels: enhancement

#96 GitHub pages update
  docs/chatbot.bot_utils.html
  docs/chatbot.decision_tree.html
  docs/index.html
  docs/intro.html
  docs/intro.md
Labels: documentation

#98 fixed park names and spelling, added a test
  src/chatbot/park_utils.clj
  src/web/backend.clj
  src/web/pages.clj
  test/chatbot/core_test.clj
Labels: bug

#99 Web
  docs/chatbot.bot_utils.html
  docs/web.backend.html
  project.clj
  src/chatbot/cli_utils.clj
  src/chatbot/core.clj
  src/web/backend.clj
  src/web/db.clj
Labels: enhancement

#101 GitHub pages update
  docs/chatbot.bot_utils.html
  docs/intro.html
  docs/intro.md
Labels: documentation

#104 103 help page
  resources/public/style.css
  src/web/backend.clj
  src/web/pages.clj
Labels: enhancement

#102 add website usage to README
  README.md
Labels: documentation

#100 089 website styling
  resources/public/script.js
  resources/public/style.css
  src/web/pages.clj
Labels: enhancement
